const services = [
    'store',
    'session',
    'current-user',
    'fetch',
    'socket',
    'media',
    'app-cache',
    'url-search-params',
    'modals-manager',
    'resource-context-panel',
    'custom-fields-registry',
    'table-context',
    'loader',
    'filters',
    'crud',
    'notifications',
    'hostRouter',
    'fileQueue',
    'sidebar',
    'dashboard',
    'universe',
    'intl',
    'abilities',
];

export default services;
