#! /bin/sh
ember g util api-url
ember g util apply-column-filters
ember g util auto-serialize
ember g util calculate-percentage
ember g util close-sidebar
ember g util console-url
ember g util copy-to-clipboard
ember g util corslite
ember g util extract-coordinates
ember g util extract-latitude
ember g util extract-longitude
ember g util find-closest-waypoint
ember g util first
ember g util format-currency
ember g util frontend-url
ember g util get-currency
ember g util get-length-units
ember g util get-meta-field-types
ember g util get-mime-type
ember g util get-model-name
ember g util get-permission-action
ember g util get-permission-resource
ember g util get-pod-methods
ember g util get-routing-host
ember g util get-service-name
ember g util get-weight-units
ember g util group-api-events
ember g util group-by
ember g util hason-structure
ember g util haversine
ember g util humanize
ember g util is-electron
ember g util is-email
ember g util is-function
ember g util is-image-file
ember g util is-iterable
ember g util ison.js
ember g util is-latitude
ember g util is-letter
ember g util is-longitude
ember g util is-model
ember g util is-not-empty
ember g util is-not-model
ember g util is-numeric
ember g util is-object
ember g util is-proxy
ember g util is-relation-missing
ember g util is-valid-coordinates
ember g util is-video-file
ember g util is-waypoint-record
ember g util isset
ember g util last
ember g util lazy-load-script
ember g util leaflet-icon
ember g util leaflet-points-from-coordinates
ember g util make-dataset
ember g util mock-response
ember g util numbers-only
ember g util past-tense
ember g util path-to-route
ember g util polyline
ember g util range
ember g util refresh-route
ember g util replace-table-row
ember g util reverse-point
ember g util set-column-filter-options
ember g util strip-html
ember g util to-leaflet-bounds
ember g util to-model
ember g util waypoint-label
ember g util with-default-value
ember g util words